// Builds supabase/seed.sql from catalog.mjs + scenario script.
// Run: pnpm --filter @kora/demo-assets seed   (images: pnpm --filter @kora/demo-assets generate)
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { catalogSql, json, q } from './catalog-sql.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, '../../supabase/seed.sql');

const USERS = {
  admin: { id: '00000000-0000-4000-a000-000000000001', email: 'admin@example.com', name: 'Admin Demo' },
  seller: { id: '00000000-0000-4000-a000-000000000002', email: 'vendedor@example.com', name: 'Vendedor Demo (OdontoPro)' },
  seller2: { id: '00000000-0000-4000-a000-000000000003', email: 'tiendas@example.com', name: 'Vendedora Demo (Hogar y Mascotas)' },
  buyer: { id: '00000000-0000-4000-a000-000000000004', email: 'comprador@example.com', name: 'Comprador Demo' },
  buyer2: { id: '00000000-0000-4000-a000-000000000005', email: 'compradora@example.com', name: 'Compradora Demo' },
};

let sql = `-- =====================================================================
-- GENERATED by tools/demo-assets/build-seed.mjs — do not edit by hand.
-- Development / demo data ONLY. Every record is flagged is_demo or is_test.
-- Demo accounts (password for all: Demo-1234 — local development only):
${Object.values(USERS).map((u) => `--   ${u.email}`).join('\n')}
-- =====================================================================
set check_function_bodies = off;

-- ---------- demo users (Supabase Auth) ----------
`;
for (const u of Object.values(USERS)) {
  sql += `insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data,
  created_at, updated_at, confirmation_token, recovery_token, email_change_token_new, email_change, email_change_token_current, reauthentication_token, phone_change, phone_change_token)
values ('00000000-0000-0000-0000-000000000000', ${q(u.id)}, 'authenticated', 'authenticated', ${q(u.email)}, extensions.crypt('Demo-1234', extensions.gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}', ${json({ full_name: u.name })}, now(), now(), '', '', '', '', '', '', '', '');
insert into auth.identities (id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values (gen_random_uuid(), ${q(u.id)}, ${q(u.id)}, ${json({ sub: u.id, email: u.email, email_verified: true })}, 'email', now(), now(), now());
`;
}
sql += `update public.profiles set is_demo = true, phone = '+58 412 000 0000' where id in (${Object.values(USERS).map((u) => q(u.id)).join(',')});
insert into public.user_roles (user_id, role) values (${q(USERS.admin.id)}, 'superadmin');

-- ---------- categories & brands ----------
`;
sql += catalogSql({ owners: Object.fromEntries(Object.entries(USERS).map(([k, u]) => [k, u.id])) });

sql += readFileSync(join(here, 'seed-config.sql'), 'utf8');
sql += readFileSync(join(here, 'seed-scenarios.sql'), 'utf8').replace(/\{\{(\w+)\}\}/g, (_, k) => USERS[k].id);
writeFileSync(out, sql);
console.log('wrote', out, `(${(sql.length / 1024).toFixed(0)} KB)`);
