// Builds supabase/seed.sql from catalog.mjs + scenario script.
// Run: pnpm --filter @kora/demo-assets seed   (images: pnpm --filter @kora/demo-assets generate)
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { brands, categories, collections, products, stores } from './catalog.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, '../../supabase/seed.sql');
const manifestPath = join(here, '../../supabase/seed-assets/manifest.json');
const manifest = existsSync(manifestPath) ? JSON.parse(readFileSync(manifestPath, 'utf8')) : {};

const q = (v) => (v === null || v === undefined ? 'null' : typeof v === 'number' ? String(v) : `'${String(v).replace(/'/g, "''")}'`);
const arr = (a) => (a && a.length ? `array[${a.map(q).join(',')}]::text[]` : `'{}'::text[]`);
const json = (o) => `${q(JSON.stringify(o ?? {}))}::jsonb`;

const USERS = {
  admin: { id: '00000000-0000-4000-a000-000000000001', email: 'admin@example.com', name: 'Admin Demo' },
  seller: { id: '00000000-0000-4000-a000-000000000002', email: 'vendedor@example.com', name: 'Vendedor Demo (OdontoPro)' },
  seller2: { id: '00000000-0000-4000-a000-000000000003', email: 'tiendas@example.com', name: 'Vendedora Demo (Hogar y Mascotas)' },
  buyer: { id: '00000000-0000-4000-a000-000000000004', email: 'comprador@example.com', name: 'Comprador Demo' },
  buyer2: { id: '00000000-0000-4000-a000-000000000005', email: 'compradora@example.com', name: 'Compradora Demo' },
};

let sql = `-- =====================================================================
-- GENERATED by tools/demo-assets/build-seed.mjs — do not edit by hand.
-- Development / demo data ONLY. Every record is flagged is_demo or is_test.
-- Demo accounts (password for all: Demo-1234 — local development only):
${Object.values(USERS).map((u) => `--   ${u.email}`).join('\n')}
-- =====================================================================
set check_function_bodies = off;

-- ---------- demo users (Supabase Auth) ----------
`;
for (const u of Object.values(USERS)) {
  sql += `insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data,
  created_at, updated_at, confirmation_token, recovery_token, email_change_token_new, email_change, email_change_token_current, reauthentication_token, phone_change, phone_change_token)
values ('00000000-0000-0000-0000-000000000000', ${q(u.id)}, 'authenticated', 'authenticated', ${q(u.email)}, extensions.crypt('Demo-1234', extensions.gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}', ${json({ full_name: u.name })}, now(), now(), '', '', '', '', '', '', '', '');
insert into auth.identities (id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values (gen_random_uuid(), ${q(u.id)}, ${q(u.id)}, ${json({ sub: u.id, email: u.email, email_verified: true })}, 'email', now(), now(), now());
`;
}
sql += `update public.profiles set is_demo = true, phone = '+58 412 000 0000' where id in (${Object.values(USERS).map((u) => q(u.id)).join(',')});
insert into public.user_roles (user_id, role) values (${q(USERS.admin.id)}, 'superadmin');

-- ---------- categories & brands ----------
`;
for (const c of categories) {
  sql += `insert into public.categories (slug, name, icon, tone, sort, risk_level, requires_review, parent_id) values (${q(c.slug)}, ${q(c.name)}, ${q(c.icon)}, ${q(c.tone)}, ${c.sort}, ${q(c.risk ?? 'low')}, ${c.review ? 'true' : 'false'}, ${c.parent ? `(select id from public.categories where slug = ${q(c.parent)})` : 'null'});\n`;
}
for (const b of brands) sql += `insert into public.brands (slug, name, official_url) values (${q(b.slug)}, ${q(b.name)}, ${q(b.url)});\n`;

sql += `\n-- ---------- stores ----------\n`;
for (const s of stores) {
  sql += `insert into public.stores (slug, name, tagline, description, logo_path, cover_path, accent, kind, status, shipping_info, policies, contact_email, is_demo)
values (${q(s.slug)}, ${q(s.name)}, ${q(s.tagline)}, ${q(s.description)}, ${q(`demo/${s.slug}-logo.webp`)}, ${q(`demo/${s.slug}-cover.webp`)}, ${q(s.accent)}, ${q(s.kind)}, ${q(s.status)}, ${q(s.shipping)},
  ${json({ returns: 'Cambios dentro de 7 días si el producto está sin uso y en su empaque (texto de demostración).', warranty: 'Según fabricante (texto de demostración).' })}, ${q(`${s.slug}@example.com`)}, true);\n`;
  if (s.owner) sql += `insert into public.store_members (store_id, user_id, role) values ((select id from public.stores where slug = ${q(s.slug)}), ${q(USERS[s.owner].id)}, 'owner');\n`;
}
sql += `insert into public.store_members (store_id, user_id, role) values ((select id from public.stores where slug = 'kora'), ${q(USERS.admin.id)}, 'owner');
insert into public.commission_rules (store_id, category_id, rate_pct, note) values ((select id from public.stores where slug = 'odontopro'), null, 12, 'Demo: comisión acordada');
insert into public.commission_rules (store_id, category_id, rate_pct, note) values (null, (select id from public.categories where slug = 'mascotas'), 8, 'Demo: categoría mascotas');
`;

sql += `\n-- ---------- products ----------\n`;
for (const p of products) {
  const imgs = manifest[p.slug] ?? [`demo/${p.slug}-1.webp`];
  sql += `insert into public.products (store_id, category_id, brand_id, slug, title, subtitle, description, highlights, option_names, origin, availability, moderation_status, compare_at_usd, weight_kg, is_demo, popularity, moderation_note)
values ((select id from public.stores where slug = ${q(p.store)}), (select id from public.categories where slug = ${q(p.category)}), ${p.brand ? `(select id from public.brands where slug = ${q(p.brand)})` : 'null'},
  ${q(p.slug)}, ${q(p.title)}, ${q(p.subtitle)}, ${q(p.description)}, ${arr(p.highlights)}, ${arr(p.options ?? [])}, ${q(p.origin)}, ${q(p.availability)}, ${q(p.moderation ?? 'published')}, ${q(p.compareAt ?? null)}, ${p.weight}, true, ${p.popularity ?? 0},
  ${p.moderation === 'pending' ? q('Requiere documentación sanitaria (demo).') : 'null'});\n`;
  p.variants.forEach((v, i) => {
    sql += `insert into public.product_variants (product_id, sku, title, options, price_usd, stock, sort) values ((select id from public.products where slug = ${q(p.slug)}), ${q(`DEMO-${p.slug.toUpperCase().slice(0, 24)}-${i + 1}`)}, ${q(v.title)}, ${json(v.options ?? {})}, ${v.price}, ${v.stock === null ? 'null' : v.stock}, ${i});\n`;
  });
  imgs.forEach((path, i) => {
    sql += `insert into public.product_images (product_id, path, alt, sort, width, height, is_demo_asset) values ((select id from public.products where slug = ${q(p.slug)}), ${q(path)}, ${q(p.title)}, ${i}, 800, 1000, true);\n`;
  });
}
// products whose variants have stock 0 for every unit were seeded as sold_out explicitly; keep availability as defined
sql += `\n-- ---------- collections ----------\n`;
for (const c of collections) {
  sql += `insert into public.collections (slug, title, subtitle, tone, layout, sort) values (${q(c.slug)}, ${q(c.title)}, ${q(c.subtitle)}, ${q(c.tone)}, ${q(c.layout)}, ${c.sort});\n`;
  products.filter((p) => (p.collections ?? []).includes(c.slug)).forEach((p, i) => {
    sql += `insert into public.collection_products (collection_id, product_id, sort) values ((select id from public.collections where slug = ${q(c.slug)}), (select id from public.products where slug = ${q(p.slug)}), ${i});\n`;
  });
}

sql += readFileSync(join(here, 'seed-config.sql'), 'utf8');
sql += readFileSync(join(here, 'seed-scenarios.sql'), 'utf8').replace(/\{\{(\w+)\}\}/g, (_, k) => USERS[k].id);
writeFileSync(out, sql);
console.log('wrote', out, `(${(sql.length / 1024).toFixed(0)} KB)`);
