// Demo catalog definition — single source for generated images and supabase/seed.sql.
//
// IMPORTANT
//  * Every record is flagged is_demo. Prices are DEMONSTRATION values, not current market prices.
//  * Brand names (UGREEN, SHEGLAM) identify the kind of product the business plans to sell; product
//    copy avoids technical claims that were not verified against official sources. Images are
//    generated illustrations (not brand photography) and are replaceable via the admin panel.

export const categories = [
  { slug: 'tecnologia', name: 'Tecnología', icon: 'cpu', tone: 'mist', sort: 1 },
  { slug: 'cargadores', name: 'Cargadores', parent: 'tecnologia', icon: 'plug-zap', tone: 'mist', sort: 1 },
  { slug: 'hubs-y-cables', name: 'Hubs y cables', parent: 'tecnologia', icon: 'cable', tone: 'mist', sort: 2 },
  { slug: 'power-banks', name: 'Power banks', parent: 'tecnologia', icon: 'battery-charging', tone: 'mist', sort: 3 },
  { slug: 'audio', name: 'Audio', icon: 'headphones', tone: 'lilac', sort: 2 },
  { slug: 'belleza', name: 'Belleza', icon: 'sparkles', tone: 'blush', sort: 3 },
  { slug: 'labios', name: 'Labios', parent: 'belleza', icon: 'heart', tone: 'blush', sort: 1 },
  { slug: 'rostro', name: 'Rostro', parent: 'belleza', icon: 'sun', tone: 'blush', sort: 2 },
  { slug: 'accesorios-belleza', name: 'Accesorios de belleza', parent: 'belleza', icon: 'brush', tone: 'blush', sort: 3 },
  { slug: 'odontologia', name: 'Odontología', icon: 'toothbrush', tone: 'sage', sort: 4, risk: 'restricted', review: true },
  { slug: 'instrumental', name: 'Instrumental', parent: 'odontologia', icon: 'scissors', tone: 'sage', sort: 1, risk: 'restricted', review: true },
  { slug: 'consumibles', name: 'Consumibles', parent: 'odontologia', icon: 'package', tone: 'sage', sort: 2, risk: 'restricted', review: true },
  { slug: 'equipamiento', name: 'Equipamiento', parent: 'odontologia', icon: 'zap', tone: 'sage', sort: 3, risk: 'regulated', review: true },
  { slug: 'hogar', name: 'Hogar', icon: 'lamp', tone: 'sand', sort: 5 },
  { slug: 'mascotas', name: 'Mascotas', icon: 'paw-print', tone: 'clay', sort: 6 },
  { slug: 'accesorios', name: 'Accesorios', icon: 'watch', tone: 'sand', sort: 7 },
];

export const brands = [
  { slug: 'ugreen', name: 'UGREEN', url: 'https://www.ugreen.com/' },
  { slug: 'sheglam', name: 'SHEGLAM', url: 'https://www.sheglam.com/' },
];

export const stores = [
  { slug: 'kora', name: 'Kora', kind: 'platform', status: 'active', accent: 'plum', monogram: 'K', tone: 'mist',
    tagline: 'Selección propia con envío desde Venezuela', shipping: 'Despachos desde Caracas. Encargos internacionales con anticipo.',
    description: 'La tienda de la plataforma: tecnología, belleza y accesorios seleccionados, en stock local o por encargo.' },
  { slug: 'odontopro', name: 'OdontoPro Suministros', kind: 'seller', status: 'active', accent: 'sky', monogram: 'OP', tone: 'sage', owner: 'seller',
    tagline: 'Insumos para consultorios', shipping: 'Envíos nacionales con MRW y Zoom (tarifas de demostración).',
    description: 'Tienda de demostración de suministros odontológicos. Los productos regulados pasan revisión antes de publicarse.' },
  { slug: 'casa-lumen', name: 'Casa Lumen', kind: 'seller', status: 'active', accent: 'amber', monogram: 'CL', tone: 'sand', owner: 'seller2',
    tagline: 'Objetos cálidos para el hogar', shipping: 'Despacho en 24 a 48 h hábiles desde Valencia.',
    description: 'Tienda de demostración de hogar y decoración.' },
  { slug: 'patitas', name: 'Patitas & Co.', kind: 'seller', status: 'active', accent: 'coral', monogram: 'P', tone: 'clay', owner: 'seller2',
    tagline: 'Todo para tus mascotas', shipping: 'Envíos a todo el país.',
    description: 'Tienda de demostración de accesorios para mascotas.' },
  { slug: 'nova-gadgets', name: 'Nova Gadgets', kind: 'seller', status: 'pending', accent: 'plum', monogram: 'N', tone: 'lilac', owner: 'seller2',
    tagline: 'Solicitud de tienda en revisión', shipping: '', description: 'Tienda pendiente de aprobación (demostración).' },
];

// color helpers for variants
const C = {
  white: '#F4F2EE', black: '#2A2C30', graphite: '#4A4F57', silver: '#C9CDD2', navy: '#2D3B5A', sage: '#8BA48A', rose: '#D9A3A0',
  nude: '#C98F7E', terracotta: '#B5573E', red: '#B3252E', berry: '#7D2E46', gold: '#C9A15A', cream: '#EDE3D1', oak: '#B98A5A',
  teal: '#2F8A80', mustard: '#D2A33A', sky: '#7FB0D8', lilac: '#A796C7', coral: '#E07A62', olive: '#7A7F4A', blue: '#2E6FB3',
};

/**
 * archetype: illustration recipe in generate-images.mjs
 * stock: null = unlimited (on_order); number = allocable units
 */
export const products = [
  // ---------------- Kora (platform) · tecnología ----------------
  { slug: 'ugreen-nexode-65w', store: 'kora', category: 'cargadores', brand: 'ugreen', archetype: 'charger', color: C.white,
    title: 'UGREEN Nexode cargador GaN 65 W', subtitle: 'Carga laptop, tablet y teléfono',
    description: 'Cargador de pared con tecnología GaN y varios puertos USB. Revisa la ficha oficial del fabricante para compatibilidad exacta antes de comprar.',
    highlights: ['Tecnología GaN', 'Varios puertos', 'Formato compacto'], availability: 'available', origin: 'local', weight: 0.25,
    options: ['Color'], variants: [{ title: 'Blanco', options: { Color: 'Blanco' }, price: 42, stock: 14, color: C.white }, { title: 'Negro', options: { Color: 'Negro' }, price: 42, stock: 6, color: C.black }],
    compareAt: null, collections: ['esenciales-tech', 'regalos'], popularity: 92 },
  { slug: 'ugreen-nexode-100w', store: 'kora', category: 'cargadores', brand: 'ugreen', archetype: 'charger', color: C.graphite, variantStyle: 'big',
    title: 'UGREEN Nexode cargador GaN 100 W', subtitle: 'Para estaciones de trabajo con varios equipos',
    description: 'Cargador GaN de alta potencia para varios dispositivos a la vez. Producto por encargo: lo compramos para ti al confirmar tu anticipo.',
    highlights: ['Por encargo', 'Alta potencia', 'Varios puertos'], availability: 'on_order', origin: 'import', weight: 0.4,
    variants: [{ title: 'Gris', price: 78, stock: null }], collections: ['esenciales-tech'], popularity: 60 },
  { slug: 'ugreen-nexode-30w', store: 'kora', category: 'cargadores', brand: 'ugreen', archetype: 'charger', color: C.white, variantStyle: 'mini',
    title: 'UGREEN Nexode cargador GaN 30 W', subtitle: 'Compacto para el día a día',
    description: 'Cargador de un puerto USB-C, ideal para teléfono y audífonos.',
    highlights: ['Tamaño mini', 'USB-C'], availability: 'available', origin: 'local', weight: 0.1,
    variants: [{ title: 'Blanco', price: 19, stock: 30 }], popularity: 70 },
  { slug: 'ugreen-revodok-hub-6-en-1', store: 'kora', category: 'hubs-y-cables', brand: 'ugreen', archetype: 'hub', color: C.graphite,
    title: 'UGREEN Revodok hub USB-C 6 en 1', subtitle: 'HDMI, USB y lector de tarjetas',
    description: 'Adaptador multipuerto para laptops con USB-C. Verifica los puertos de tu equipo antes de comprar.',
    highlights: ['Multipuerto', 'Aluminio', 'Plug and play'], availability: 'available', origin: 'local', weight: 0.12,
    variants: [{ title: 'Gris espacial', price: 36, stock: 9 }], collections: ['esenciales-tech'], popularity: 80 },
  { slug: 'ugreen-hub-usb-c-10-en-1', store: 'kora', category: 'hubs-y-cables', brand: 'ugreen', archetype: 'hub', color: C.silver, variantStyle: 'long',
    title: 'UGREEN hub USB-C 10 en 1', subtitle: 'Estación completa para escritorio',
    description: 'Hub de escritorio con múltiples salidas. Disponible por encargo internacional.',
    highlights: ['Por encargo', 'Para escritorio'], availability: 'on_order', origin: 'import', weight: 0.3,
    variants: [{ title: 'Plata', price: 64, stock: null }], popularity: 40 },
  { slug: 'ugreen-cable-usb-c-100w', store: 'kora', category: 'hubs-y-cables', brand: 'ugreen', archetype: 'cable', color: C.black,
    title: 'UGREEN cable USB-C a USB-C', subtitle: 'Trenzado, para carga rápida',
    description: 'Cable trenzado de USB-C a USB-C para carga y datos.',
    highlights: ['Trenzado', 'USB-C a USB-C'], availability: 'available', origin: 'local', weight: 0.06,
    options: ['Largo'], variants: [{ title: '1 m', options: { Largo: '1 m' }, price: 9, stock: 40 }, { title: '2 m', options: { Largo: '2 m' }, price: 12, stock: 25 }],
    collections: ['regalos'], popularity: 85 },
  { slug: 'ugreen-cable-usb-c-lightning', store: 'kora', category: 'hubs-y-cables', brand: 'ugreen', archetype: 'cable', color: C.white,
    title: 'UGREEN cable USB-C a Lightning', subtitle: 'Para iPhone con conector Lightning',
    description: 'Cable de carga para dispositivos Apple con puerto Lightning. Lote en camino a Venezuela.',
    highlights: ['En camino', 'Lightning'], availability: 'in_transit', origin: 'local', weight: 0.06,
    variants: [{ title: '1 m', price: 13, stock: 20 }], popularity: 45 },
  { slug: 'ugreen-power-bank-20000', store: 'kora', category: 'power-banks', brand: 'ugreen', archetype: 'powerbank', color: C.graphite,
    title: 'UGREEN Nexode power bank 20.000 mAh', subtitle: 'Batería portátil de alta capacidad',
    description: 'Batería externa de alta capacidad con salidas USB-C y USB-A.',
    highlights: ['20.000 mAh', 'USB-C'], availability: 'available', origin: 'local', weight: 0.5,
    variants: [{ title: 'Gris', price: 55, stock: 2 }], collections: ['esenciales-tech'], popularity: 88 },
  { slug: 'ugreen-power-bank-magnetico', store: 'kora', category: 'power-banks', brand: 'ugreen', archetype: 'powerbank', color: C.sky, variantStyle: 'slim',
    title: 'UGREEN power bank magnético 10.000 mAh', subtitle: 'Se adhiere a la parte trasera del teléfono',
    description: 'Batería magnética compacta. Reserva una unidad del próximo lote.',
    highlights: ['Magnético', 'Reservable'], availability: 'reservable', origin: 'local', weight: 0.22,
    variants: [{ title: 'Azul', price: 38, stock: 12, color: C.sky }], popularity: 50 },
  { slug: 'ugreen-soporte-laptop', store: 'kora', category: 'tecnologia', brand: 'ugreen', archetype: 'stand', color: C.silver,
    title: 'UGREEN soporte de aluminio para laptop', subtitle: 'Eleva la pantalla a la altura de los ojos',
    description: 'Soporte plegable y ajustable para laptops.',
    highlights: ['Plegable', 'Ajustable'], availability: 'available', origin: 'local', weight: 0.9,
    variants: [{ title: 'Plata', price: 32, stock: 7 }], popularity: 55 },
  { slug: 'ugreen-cargador-auto', store: 'kora', category: 'cargadores', brand: 'ugreen', archetype: 'carcharger', color: C.black,
    title: 'UGREEN cargador de auto USB-C', subtitle: 'Dos puertos para el camino',
    description: 'Cargador para el encendedor del vehículo. Por encargo.',
    highlights: ['Por encargo', 'Dos puertos'], availability: 'on_order', origin: 'import', weight: 0.08,
    variants: [{ title: 'Negro', price: 21, stock: null }], popularity: 30 },
  { slug: 'teclado-mecanico-compacto', store: 'kora', category: 'tecnologia', brand: null, archetype: 'keyboard', color: C.cream,
    title: 'Teclado mecánico compacto', subtitle: 'Formato 75 %, inalámbrico',
    description: 'Teclado mecánico compacto de producto genérico de demostración. Por encargo.',
    highlights: ['Por encargo', 'Inalámbrico'], availability: 'on_order', origin: 'import', weight: 0.9,
    options: ['Color'], variants: [{ title: 'Crema', options: { Color: 'Crema' }, price: 69, stock: null, color: C.cream }, { title: 'Grafito', options: { Color: 'Grafito' }, price: 69, stock: null, color: C.graphite }],
    collections: ['nuevos-encargos'], popularity: 58 },

  // ---------------- audio ----------------
  { slug: 'audifonos-anc-over-ear', store: 'kora', category: 'audio', brand: null, archetype: 'headphones', color: C.sage,
    title: 'Audífonos inalámbricos con cancelación de ruido', subtitle: 'Over-ear, plegables',
    description: 'Audífonos over-ear genéricos de demostración. Por encargo internacional.',
    highlights: ['Por encargo', 'Plegables'], availability: 'on_order', origin: 'import', weight: 0.35,
    options: ['Color'], variants: [{ title: 'Salvia', options: { Color: 'Salvia' }, price: 89, stock: null, color: C.sage }, { title: 'Arena', options: { Color: 'Arena' }, price: 89, stock: null, color: C.cream }],
    collections: ['nuevos-encargos'], popularity: 76 },
  { slug: 'audifonos-in-ear-estuche', store: 'kora', category: 'audio', brand: null, archetype: 'earbuds', color: C.white,
    title: 'Audífonos in-ear con estuche de carga', subtitle: 'Bluetooth, uso diario',
    description: 'Audífonos inalámbricos genéricos de demostración.',
    highlights: ['Bluetooth', 'Estuche de carga'], availability: 'available', origin: 'local', weight: 0.08,
    variants: [{ title: 'Blanco', price: 29, stock: 18 }], popularity: 74 },
  { slug: 'parlante-portatil', store: 'kora', category: 'audio', brand: null, archetype: 'speaker', color: C.teal,
    title: 'Parlante portátil resistente al agua', subtitle: 'Para la playa y la piscina',
    description: 'Parlante Bluetooth genérico de demostración.',
    highlights: ['Bluetooth', 'Portátil'], availability: 'available', origin: 'local', weight: 0.6,
    options: ['Color'], variants: [{ title: 'Turquesa', options: { Color: 'Turquesa' }, price: 45, stock: 5, color: C.teal }, { title: 'Coral', options: { Color: 'Coral' }, price: 45, stock: 3, color: C.coral }],
    popularity: 64 },
  { slug: 'audifonos-deportivos', store: 'kora', category: 'audio', brand: null, archetype: 'earbuds', color: C.coral, variantStyle: 'sport',
    title: 'Audífonos deportivos', subtitle: 'Con gancho para la oreja',
    description: 'Agotados por ahora. Activa el aviso y te escribimos cuando vuelvan.',
    highlights: ['Agotado'], availability: 'sold_out', origin: 'local', weight: 0.06,
    variants: [{ title: 'Coral', price: 24, stock: 0 }], popularity: 35 },

  // ---------------- belleza (SHEGLAM) ----------------
  { slug: 'sheglam-labial-liquido-mate', store: 'kora', category: 'labios', brand: 'sheglam', archetype: 'lipstick', color: C.terracotta,
    title: 'SHEGLAM labial líquido mate', subtitle: 'Acabado mate de larga duración',
    description: 'Labial líquido de acabado mate. Tonos de referencia; el color real puede variar según la pantalla.',
    highlights: ['Acabado mate', 'Varios tonos'], availability: 'available', origin: 'local', weight: 0.03,
    options: ['Tono'], variants: [
      { title: 'Rosa nude', options: { Tono: 'Rosa nude' }, price: 8, stock: 20, color: C.nude },
      { title: 'Terracota', options: { Tono: 'Terracota' }, price: 8, stock: 15, color: C.terracotta },
      { title: 'Rojo clásico', options: { Tono: 'Rojo clásico' }, price: 8, stock: 4, color: C.red }],
    collections: ['belleza-esencial', 'regalos'], popularity: 95 },
  { slug: 'sheglam-brillo-labial', store: 'kora', category: 'labios', brand: 'sheglam', archetype: 'gloss', color: C.rose,
    title: 'SHEGLAM brillo labial', subtitle: 'Brillo con efecto espejo',
    description: 'Brillo labial de acabado luminoso.',
    highlights: ['Brillante'], availability: 'available', origin: 'local', weight: 0.03,
    options: ['Tono'], variants: [{ title: 'Rosado', options: { Tono: 'Rosado' }, price: 7, stock: 22, color: C.rose }, { title: 'Baya', options: { Tono: 'Baya' }, price: 7, stock: 9, color: C.berry }],
    collections: ['belleza-esencial'], popularity: 82 },
  { slug: 'sheglam-base-fluida', store: 'kora', category: 'rostro', brand: 'sheglam', archetype: 'foundation', color: C.nude,
    title: 'SHEGLAM base de maquillaje fluida', subtitle: 'Cobertura media',
    description: 'Base líquida en varios tonos. Disponible por encargo para garantizar tu tono.',
    highlights: ['Por encargo', 'Varios tonos'], availability: 'on_order', origin: 'import', weight: 0.08,
    options: ['Tono'], variants: [
      { title: 'Claro', options: { Tono: 'Claro' }, price: 14, stock: null, color: '#E9C6A8' },
      { title: 'Medio', options: { Tono: 'Medio' }, price: 14, stock: null, color: '#C99A72' },
      { title: 'Profundo', options: { Tono: 'Profundo' }, price: 14, stock: null, color: '#8A5B3D' }],
    popularity: 66 },
  { slug: 'sheglam-rubor-liquido', store: 'kora', category: 'rostro', brand: 'sheglam', archetype: 'blush', color: C.coral,
    title: 'SHEGLAM rubor líquido', subtitle: 'Color difuminable',
    description: 'Rubor en formato líquido con aplicador.',
    highlights: ['Fácil de difuminar'], availability: 'available', origin: 'local', weight: 0.03,
    variants: [{ title: 'Coral', price: 9, stock: 11 }], collections: ['belleza-esencial'], popularity: 78 },
  { slug: 'sheglam-paleta-sombras', store: 'kora', category: 'rostro', brand: 'sheglam', archetype: 'palette', color: C.terracotta,
    title: 'SHEGLAM paleta de sombras', subtitle: 'Tonos cálidos',
    description: 'Paleta de sombras en gama cálida. Lote en camino.',
    highlights: ['En camino', 'Tonos cálidos'], availability: 'in_transit', origin: 'local', weight: 0.15,
    variants: [{ title: 'Cálidos', price: 16, stock: 10 }], popularity: 61 },
  { slug: 'sheglam-set-brochas', store: 'kora', category: 'accesorios-belleza', brand: 'sheglam', archetype: 'brushes', color: C.rose,
    title: 'SHEGLAM set de brochas', subtitle: 'Rostro y ojos',
    description: 'Set de brochas para maquillaje.',
    highlights: ['Set completo'], availability: 'available', origin: 'local', weight: 0.2,
    variants: [{ title: 'Set', price: 18, stock: 8 }], collections: ['regalos'], popularity: 57 },
  { slug: 'sheglam-polvo-sellador', store: 'kora', category: 'rostro', brand: 'sheglam', archetype: 'compact', color: C.cream,
    title: 'SHEGLAM polvo sellador', subtitle: 'Acabado natural',
    description: 'Polvo compacto. Reserva tu unidad del próximo lote.',
    highlights: ['Reservable'], availability: 'reservable', origin: 'local', weight: 0.05,
    variants: [{ title: 'Translúcido', price: 11, stock: 15 }], popularity: 49 },
  { slug: 'esponjas-maquillaje-x4', store: 'kora', category: 'accesorios-belleza', brand: null, archetype: 'sponge', color: C.rose,
    title: 'Esponjas de maquillaje · pack x4', subtitle: 'Uso en seco o húmedo',
    description: 'Esponjas genéricas de demostración.',
    highlights: ['Pack x4'], availability: 'available', origin: 'local', weight: 0.04,
    variants: [{ title: 'Pack x4', price: 6, stock: 35 }], popularity: 52 },

  // ---------------- accesorios ----------------
  { slug: 'reloj-inteligente-deportivo', store: 'kora', category: 'accesorios', brand: null, archetype: 'watch', color: C.black,
    title: 'Reloj inteligente deportivo', subtitle: 'Notificaciones y actividad',
    description: 'Reloj inteligente genérico de demostración. Por encargo.',
    highlights: ['Por encargo'], availability: 'on_order', origin: 'import', weight: 0.1,
    options: ['Color'], variants: [{ title: 'Negro', options: { Color: 'Negro' }, price: 59, stock: null, color: C.black }, { title: 'Oliva', options: { Color: 'Oliva' }, price: 59, stock: null, color: C.olive }],
    collections: ['nuevos-encargos'], popularity: 63 },
  { slug: 'mochila-urbana-laptop', store: 'kora', category: 'accesorios', brand: null, archetype: 'backpack', color: C.navy,
    title: 'Mochila urbana para laptop', subtitle: 'Compartimento acolchado',
    description: 'Mochila genérica de demostración con compartimento para laptop.',
    highlights: ['Acolchada'], availability: 'available', origin: 'local', weight: 0.8,
    options: ['Color'], variants: [{ title: 'Azul marino', options: { Color: 'Azul marino' }, price: 39, stock: 6, color: C.navy }, { title: 'Oliva', options: { Color: 'Oliva' }, price: 39, stock: 4, color: C.olive }],
    popularity: 47 },

  // ---------------- OdontoPro (seller · regulated categories) ----------------
  { slug: 'espejos-bucales-x12', store: 'odontopro', category: 'instrumental', brand: null, archetype: 'mirrors', color: C.silver,
    title: 'Espejos bucales planos · caja x12', subtitle: 'Acero inoxidable',
    description: 'Espejos bucales para uso profesional. Producto de demostración.',
    highlights: ['Uso profesional', 'Caja x12'], availability: 'available', origin: 'seller', weight: 0.2,
    variants: [{ title: 'Caja x12', price: 15, stock: 25 }], collections: ['consultorio'], popularity: 44 },
  { slug: 'kit-exploradores-pinzas', store: 'odontopro', category: 'instrumental', brand: null, archetype: 'instruments', color: C.silver,
    title: 'Kit de exploradores y pinzas', subtitle: 'Set básico de examen',
    description: 'Set básico de instrumental de examen. Producto de demostración.',
    highlights: ['Set básico'], availability: 'available', origin: 'seller', weight: 0.25,
    variants: [{ title: 'Kit', price: 22, stock: 10 }], collections: ['consultorio'], popularity: 38 },
  { slug: 'guantes-nitrilo-x100', store: 'odontopro', category: 'consumibles', brand: null, archetype: 'glovebox', color: C.blue,
    title: 'Guantes de nitrilo sin polvo · caja x100', subtitle: 'Consumible de consultorio',
    description: 'Guantes de nitrilo desechables. Producto de demostración.',
    highlights: ['Sin polvo', 'Caja x100'], availability: 'available', origin: 'seller', weight: 0.6,
    options: ['Talla'], variants: [{ title: 'S', options: { Talla: 'S' }, price: 9, stock: 12 }, { title: 'M', options: { Talla: 'M' }, price: 9, stock: 30 }, { title: 'L', options: { Talla: 'L' }, price: 9, stock: 0 }],
    collections: ['consultorio'], popularity: 68 },
  { slug: 'eyectores-saliva-x100', store: 'odontopro', category: 'consumibles', brand: null, archetype: 'ejectors', color: C.sky,
    title: 'Eyectores de saliva · bolsa x100', subtitle: 'Desechables',
    description: 'Eyectores desechables. Producto de demostración.',
    highlights: ['Bolsa x100'], availability: 'available', origin: 'seller', weight: 0.3,
    variants: [{ title: 'Bolsa x100', price: 6, stock: 40 }], popularity: 33 },
  { slug: 'baberos-desechables-x125', store: 'odontopro', category: 'consumibles', brand: null, archetype: 'bibs', color: C.sky,
    title: 'Baberos desechables · paquete x125', subtitle: 'Doble capa',
    description: 'Baberos desechables para pacientes. Producto de demostración.',
    highlights: ['Paquete x125'], availability: 'available', origin: 'seller', weight: 1.1,
    variants: [{ title: 'Celeste', price: 12, stock: 14 }], popularity: 29 },
  { slug: 'lampara-fotocurado-led', store: 'odontopro', category: 'equipamiento', brand: null, archetype: 'curinglight', color: C.white,
    title: 'Lámpara de fotocurado LED inalámbrica', subtitle: 'Equipamiento profesional',
    description: 'Equipo profesional. Pendiente de revisión: requiere verificar documentación sanitaria antes de publicarse.',
    highlights: ['Requiere revisión'], availability: 'on_order', origin: 'seller', weight: 0.4,
    variants: [{ title: 'Unidad', price: 120, stock: null }], moderation: 'pending', popularity: 10 },
  { slug: 'cubetas-impresion-set', store: 'odontopro', category: 'instrumental', brand: null, archetype: 'trays', color: C.silver,
    title: 'Cubetas de impresión · set', subtitle: 'Superior e inferior',
    description: 'Set de cubetas de impresión. Producto de demostración.',
    highlights: ['Set'], availability: 'available', origin: 'seller', weight: 0.5,
    variants: [{ title: 'Set', price: 26, stock: 6 }], popularity: 21 },

  // ---------------- Casa Lumen (seller · hogar) ----------------
  { slug: 'lampara-mesa-lino', store: 'casa-lumen', category: 'hogar', brand: null, archetype: 'lamp', color: C.oak,
    title: 'Lámpara de mesa con pantalla de lino', subtitle: 'Luz cálida para el salón',
    description: 'Lámpara de mesa de demostración con base de madera.',
    highlights: ['Pantalla de lino'], availability: 'available', origin: 'seller', weight: 1.6,
    variants: [{ title: 'Roble', price: 48, stock: 4 }], collections: ['casa-calida'], popularity: 59 },
  { slug: 'set-tazas-ceramica-x4', store: 'casa-lumen', category: 'hogar', brand: null, archetype: 'mugs', color: C.teal,
    title: 'Set de tazas de cerámica · x4', subtitle: 'Esmaltado artesanal',
    description: 'Tazas de demostración con acabado esmaltado.',
    highlights: ['Set x4'], availability: 'available', origin: 'seller', weight: 1.4,
    options: ['Color'], variants: [{ title: 'Turquesa', options: { Color: 'Turquesa' }, price: 28, stock: 6, color: C.teal }, { title: 'Mostaza', options: { Color: 'Mostaza' }, price: 28, stock: 5, color: C.mustard }],
    collections: ['casa-calida', 'regalos'], popularity: 62 },
  { slug: 'vela-aromatica-vaso', store: 'casa-lumen', category: 'hogar', brand: null, archetype: 'candle', color: C.cream,
    title: 'Vela aromática en vaso de vidrio', subtitle: 'Cera vegetal',
    description: 'Vela de demostración en vaso de vidrio ámbar.',
    highlights: ['Cera vegetal'], availability: 'available', origin: 'seller', weight: 0.45,
    options: ['Aroma'], variants: [{ title: 'Vainilla', options: { Aroma: 'Vainilla' }, price: 14, stock: 10 }, { title: 'Cedro', options: { Aroma: 'Cedro' }, price: 14, stock: 7 }],
    collections: ['casa-calida'], popularity: 71 },
  { slug: 'juego-toallas-algodon', store: 'casa-lumen', category: 'hogar', brand: null, archetype: 'towels', color: C.sage,
    title: 'Juego de toallas de algodón', subtitle: 'Baño y manos',
    description: 'Juego de toallas de demostración. Lote en camino.',
    highlights: ['En camino'], availability: 'in_transit', origin: 'seller', weight: 1.2,
    variants: [{ title: 'Salvia', price: 34, stock: 8 }], popularity: 36 },
  { slug: 'organizador-bambu', store: 'casa-lumen', category: 'hogar', brand: null, archetype: 'organizer', color: C.oak,
    title: 'Organizador de bambú', subtitle: 'Para escritorio o cocina',
    description: 'Organizador de demostración.',
    highlights: ['Bambú'], availability: 'available', origin: 'seller', weight: 0.7,
    variants: [{ title: 'Natural', price: 19, stock: 9 }], popularity: 31 },

  // ---------------- Patitas (seller · mascotas) ----------------
  { slug: 'cama-ovalada-mascotas', store: 'patitas', category: 'mascotas', brand: null, archetype: 'petbed', color: C.mustard,
    title: 'Cama ovalada para mascotas', subtitle: 'Bordes acolchados',
    description: 'Cama de demostración para perros y gatos.',
    highlights: ['Acolchada'], availability: 'available', origin: 'seller', weight: 1.0,
    options: ['Tamaño'], variants: [{ title: 'S', options: { Tamaño: 'S' }, price: 24, stock: 5 }, { title: 'M', options: { Tamaño: 'M' }, price: 32, stock: 4 }, { title: 'L', options: { Tamaño: 'L' }, price: 41, stock: 2 }],
    collections: ['mascotas-felices'], popularity: 67 },
  { slug: 'comedero-doble-acero', store: 'patitas', category: 'mascotas', brand: null, archetype: 'bowl', color: C.silver,
    title: 'Comedero doble de acero inoxidable', subtitle: 'Base antideslizante',
    description: 'Comedero de demostración.',
    highlights: ['Antideslizante'], availability: 'available', origin: 'seller', weight: 0.6,
    variants: [{ title: 'Único', price: 16, stock: 11 }], collections: ['mascotas-felices'], popularity: 54 },
  { slug: 'juguete-cuerda-perros', store: 'patitas', category: 'mascotas', brand: null, archetype: 'rope', color: C.coral,
    title: 'Juguete de cuerda para perros', subtitle: 'Algodón trenzado',
    description: 'Juguete de demostración.',
    highlights: ['Algodón'], availability: 'available', origin: 'seller', weight: 0.15,
    variants: [{ title: 'Único', price: 7, stock: 25 }], popularity: 48 },
  { slug: 'rascador-gatos-torre', store: 'patitas', category: 'mascotas', brand: null, archetype: 'scratcher', color: C.cream,
    title: 'Rascador para gatos tipo torre', subtitle: 'Con plataforma',
    description: 'Rascador de demostración.',
    highlights: ['Torre'], availability: 'available', origin: 'seller', weight: 3.5,
    variants: [{ title: 'Beige', price: 52, stock: 1 }], popularity: 41 },
  { slug: 'correa-reflectiva', store: 'patitas', category: 'mascotas', brand: null, archetype: 'leash', color: C.teal,
    title: 'Correa reflectiva', subtitle: 'Para paseos nocturnos',
    description: 'Correa de demostración con costuras reflectivas.',
    highlights: ['Reflectiva'], availability: 'available', origin: 'seller', weight: 0.2,
    options: ['Color'], variants: [{ title: 'Turquesa', options: { Color: 'Turquesa' }, price: 11, stock: 15, color: C.teal }, { title: 'Coral', options: { Color: 'Coral' }, price: 11, stock: 9, color: C.coral }],
    popularity: 39 },
];

export const collections = [
  { slug: 'esenciales-tech', title: 'Esenciales para cargar todo', subtitle: 'Cargadores, hubs y baterías', tone: 'mist', layout: 'feature', sort: 1 },
  { slug: 'belleza-esencial', title: 'Belleza de todos los días', subtitle: 'Labios y rostro', tone: 'blush', layout: 'rail', sort: 2 },
  { slug: 'nuevos-encargos', title: 'Traídos para ti', subtitle: 'Por encargo, con anticipo del 50 %', tone: 'lilac', layout: 'rail', sort: 3 },
  { slug: 'casa-calida', title: 'Casa cálida', subtitle: 'De tiendas independientes', tone: 'sand', layout: 'feature', sort: 4 },
  { slug: 'regalos', title: 'Ideas para regalar', subtitle: 'Menos de 50 USD', tone: 'clay', layout: 'grid', sort: 5 },
  { slug: 'mascotas-felices', title: 'Para tus mascotas', subtitle: null, tone: 'clay', layout: 'rail', sort: 6 },
  { slug: 'consultorio', title: 'Para el consultorio', subtitle: 'Insumos de OdontoPro', tone: 'sage', layout: 'rail', sort: 7 },
];
