// Regenerates apps/mobile/src/components/ui/icon-paths.ts from lucide-static (ISC). Only the listed icons ship.
import { createRequire } from 'node:module';
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

const require = createRequire(import.meta.url);
const nodes = require('lucide-static/icon-nodes.json');
const WANT = `house search heart shopping-bag user chevron-left chevron-right chevron-down x plus minus check share-2
sliders-horizontal arrow-up-down truck package store map-pin clock shield-check circle-alert info bell copy upload camera
image receipt credit-card wallet log-out settings trash star sparkles tag box plane ship hourglass refresh-cw message-circle
lock eye eye-off funnel arrow-right circle-check banknote landmark smartphone coins badge-check cpu headphones sofa paw-print
toothbrush face-slightly-smiling stethoscope gem lamp shirt watch layout-grid flame gift calendar file-text circle-question-mark globe moon sun
monitor-smartphone zap plug-zap battery-charging scissors brush cable wifi-off`.split(/\s+/);

const lines = [
  '// Icon geometry derived from Lucide (https://lucide.dev), ISC License, Copyright (c) Lucide Icons and Contributors.',
  '// Generated by tools/demo-assets/generate-icons.mjs from lucide-static; edit the list there, not this file.',
  'export const ICONS = {',
];
for (const name of [...WANT].sort()) {
  if (!nodes[name]) throw new Error(`unknown icon ${name}`);
  const els = nodes[name].map(([tag, attrs]) => [tag, Object.fromEntries(Object.entries(attrs).filter(([k]) => k !== 'key'))]);
  lines.push(`  '${name}': ${JSON.stringify(els)},`);
}
lines.push('} as const;', 'export type IconName = keyof typeof ICONS;');
writeFileSync(join(import.meta.dirname, '../../apps/mobile/src/components/ui/icon-paths.ts'), lines.join('\n') + '\n');
console.log(`${WANT.length} icons`);
