-- =====================================================================
-- GENERATED by tools/demo-assets/build-remote-catalog.mjs — do not edit by hand.
-- Takes the demo catalog out of the hosted test project (Supabase › SQL Editor › Run).
-- If an order already uses a demo product or store, nothing is deleted: the demo stores are suspended, their
-- products hidden and the demo shipping rates turned off, so order history stays intact.
-- Payment methods go back to disabled with empty instructions only while they still hold the demo details.
-- =====================================================================
begin;

update public.payment_methods set enabled = false, instructions = '{}'
 where code in ('pago_movil', 'transferencia_ves', 'zelle', 'usdt_trc20', 'efectivo_usd') and instructions->>'nota' ilike '%fictici%de desarrollo%';

do $$
declare
  used int;
begin
  select count(*) into used from public.order_items oi join public.products p on p.id = oi.product_id where p.is_demo;
  if used > 0 then
    update public.stores set status = 'suspended' where is_demo and slug in ('kora', 'odontopro', 'casa-lumen', 'patitas', 'nova-gadgets');
    update public.products set moderation_status = 'suspended' where is_demo;
    update public.shipping_rates set active = false where is_demo;
    raise notice 'Hay pedidos con productos de demostración (% líneas): se ocultó el catálogo sin borrarlo.', used;
    return;
  end if;

  delete from public.collections where slug in ('esenciales-tech', 'belleza-esencial', 'nuevos-encargos', 'casa-calida', 'regalos', 'mascotas-felices', 'consultorio');
  delete from public.commission_rules where note like 'Demo:%';
  delete from public.products where is_demo;
  delete from public.stores where is_demo and slug in ('kora', 'odontopro', 'casa-lumen', 'patitas', 'nova-gadgets');
  delete from public.pickup_points where is_demo;
  delete from public.shipping_rates where is_demo;
  delete from public.shipping_methods m using public.carriers c
   where m.carrier_id = c.id and c.is_demo and c.code in ('kora_moto', 'zoom', 'mrw', 'tealca', 'retiro')
     and not exists (select 1 from public.shipping_rates r where r.method_id = m.id);
  delete from public.carriers c where c.is_demo and c.code in ('kora_moto', 'zoom', 'mrw', 'tealca', 'retiro')
     and not exists (select 1 from public.shipping_methods m where m.carrier_id = c.id);
  delete from public.shipping_zones z where z.code in ('caracas', 'centro', 'occidente', 'andes', 'oriente', 'sur')
     and not exists (select 1 from public.shipping_rates r where r.zone_id = z.id);
  delete from public.brands b where b.slug in ('ugreen', 'sheglam')
     and not exists (select 1 from public.products p where p.brand_id = b.id);
  -- subcategories first, then their parents, and only those no real product uses
  delete from public.categories c where c.slug in ('cargadores', 'hubs-y-cables', 'power-banks', 'labios', 'rostro', 'accesorios-belleza', 'instrumental', 'consumibles', 'equipamiento')
     and not exists (select 1 from public.products p where p.category_id = c.id);
  delete from public.categories c where c.slug in ('tecnologia', 'audio', 'belleza', 'odontologia', 'hogar', 'mascotas', 'accesorios')
     and not exists (select 1 from public.products p where p.category_id = c.id)
     and not exists (select 1 from public.categories k where k.parent_id = c.id);
  raise notice 'Catálogo de demostración eliminado.';
end $$;

commit;
